"""
EdgeFlip utility for Experiment 2.

This module implements the edge-flipping baseline for undirected network
community detection.  It is intended to be placed under ``Utility/`` and
imported by experiment scripts, for example

    from Utility.Edge_flip import run_edgeflip_from_saved

The input folders are the saved DCSBM replications generated by the simulation
utility.  Each replication folder should contain either

    A_upper_bitpack.bin

or an edge-list file such as

    A_edges.csv
    edges.csv

and should also contain ``A_eigvecs_topK.csv`` with the true labels ``z`` for
evaluating clustering error.

Main public function
--------------------
``run_edgeflip_from_saved``
    For each saved replication and each privacy budget epsilon, apply the
    edge-flipping mechanism, run spectral clustering on the privatized graph,
    and return a replication-level pandas DataFrame.
"""

from __future__ import annotations

import os
import re
import struct
from pathlib import Path
from typing import Iterable, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
from scipy.sparse import coo_matrix
from scipy.sparse.linalg import eigsh
from sklearn.cluster import KMeans


# -----------------------------------------------------------------------------
# Imports shared with the GapPTR utility
# -----------------------------------------------------------------------------

try:  # Preferred when this file is imported as Utility.Edge_flip
    from Utility.gapptr_utility import clustering_error, try_load_labels_true
except Exception:  # Fallback when this file is run from inside Utility/
    from gapptr_utility import clustering_error, try_load_labels_true


# -----------------------------------------------------------------------------
# Basic clustering and loading helpers
# -----------------------------------------------------------------------------


def _cluster_from_embedding(
    Xi: np.ndarray,
    K: int,
    nstart: int = 25,
    norm_tol: float = 1e-12,
    seed: Optional[int] = None,
) -> np.ndarray:
    """Row-normalize a spectral embedding and run k-means."""
    Xi = np.asarray(Xi, dtype=float)
    row_norm = np.sqrt((Xi * Xi).sum(axis=1))
    row_norm = np.maximum(row_norm, norm_tol)
    X_normalized = Xi / row_norm[:, None]
    km = KMeans(n_clusters=K, n_init=nstart, random_state=seed)
    return km.fit_predict(X_normalized)


def _find_rep_dir(sim_dir: str | Path, rep: int) -> Path:
    """Find a replication folder such as rep000, rep_000, or rep0000."""
    sim_dir = Path(sim_dir)
    candidates = [
        sim_dir / f"rep{rep:03d}",
        sim_dir / f"rep_{rep:03d}",
        sim_dir / f"rep{rep:04d}",
        sim_dir / f"rep_{rep:04d}",
    ]
    for path in candidates:
        if path.is_dir():
            return path
    raise FileNotFoundError(f"Cannot locate replication rep={rep} under {sim_dir}.")


def _read_n_from_meta(rep_dir: str | Path) -> Optional[int]:
    """Read n from meta.json if available."""
    import json

    path = Path(rep_dir) / "meta.json"
    if not path.exists():
        return None
    try:
        with open(path, "r", encoding="utf-8") as f:
            obj = json.load(f)
        if "n" in obj:
            return int(obj["n"])
    except Exception:
        return None
    return None


def load_edges_upper_from_csv(path: str | Path, index_base_edges: Optional[int] = None) -> Tuple[int | None, np.ndarray, np.ndarray]:
    """
    Load an undirected upper-triangle edge list from CSV.

    Returns ``(n, ei, ej)``.  The value of ``n`` is ``None`` because an edge list
    alone does not determine the number of isolated trailing nodes.  The caller
    should read ``n`` from metadata when available.
    """
    path = Path(path)
    arr = np.loadtxt(path, delimiter=",", skiprows=1, dtype=np.int64)
    if arr.size == 0:
        return None, np.empty(0, dtype=np.int64), np.empty(0, dtype=np.int64)
    if arr.ndim == 1:
        arr = arr.reshape(1, 2)

    ei = arr[:, 0].astype(np.int64)
    ej = arr[:, 1].astype(np.int64)

    if index_base_edges is None:
        min_id = int(min(ei.min(), ej.min()))
        index_base_edges = 1 if min_id >= 1 else 0

    ei = ei - int(index_base_edges)
    ej = ej - int(index_base_edges)

    swap = ei > ej
    if np.any(swap):
        tmp = ei[swap].copy()
        ei[swap] = ej[swap]
        ej[swap] = tmp

    mask = ei < ej
    return None, ei[mask], ej[mask]


def load_edges_upper_from_bitpack(path: str | Path) -> Tuple[int, np.ndarray, np.ndarray]:
    """
    Read the ABIT bit-packed upper triangle.

    The format is the one written by the simulation generator:

    * 4 bytes: magic string ``ABIT``;
    * uint32: number of nodes ``n``;
    * uint8: index-base metadata;
    * uint8: bit-order flag, where 1 means little-endian bit order;
    * remaining bytes: packed upper-triangle rows.
    """
    path = Path(path)
    with open(path, "rb") as f:
        magic = f.read(4)
        if magic != b"ABIT":
            raise ValueError(f"Bad magic {magic!r}; expected b'ABIT' in {path}.")

        n = struct.unpack("<I", f.read(4))[0]
        _index_base_meta = struct.unpack("<B", f.read(1))[0]
        bitflag = struct.unpack("<B", f.read(1))[0]
        bitorder = "little" if bitflag == 1 else "big"

        ei_chunks: list[np.ndarray] = []
        ej_chunks: list[np.ndarray] = []

        for i in range(n - 1):
            row_length = n - i - 1
            nbytes = (row_length + 7) // 8
            buf = f.read(nbytes)
            if len(buf) != nbytes:
                raise EOFError(f"ABIT file truncated at row {i}: {path}")

            packed = np.frombuffer(buf, dtype=np.uint8)
            bits = np.unpackbits(packed, bitorder=bitorder)[:row_length]
            js_rel = np.flatnonzero(bits)
            if js_rel.size == 0:
                continue

            js = js_rel + i + 1
            ei_chunks.append(np.full(js.size, i, dtype=np.int64))
            ej_chunks.append(js.astype(np.int64))

    if ei_chunks:
        ei = np.concatenate(ei_chunks)
        ej = np.concatenate(ej_chunks)
    else:
        ei = np.empty(0, dtype=np.int64)
        ej = np.empty(0, dtype=np.int64)

    return int(n), ei, ej


def load_saved_upper_edges(
    rep_dir: str | Path,
    index_base_edges: Optional[int] = None,
) -> Tuple[int, np.ndarray, np.ndarray]:
    """Load saved upper-triangle edges from a replication folder."""
    rep_dir = Path(rep_dir)

    bitpack_candidates = ["A_upper_bitpack.bin", "A_upper_bitpack_little.bin"]
    for filename in bitpack_candidates:
        path = rep_dir / filename
        if path.exists():
            return load_edges_upper_from_bitpack(path)

    csv_candidates = ["A_edges.csv", "edges.csv"]
    for filename in csv_candidates:
        path = rep_dir / filename
        if path.exists():
            n_meta = _read_n_from_meta(rep_dir)
            _n, ei, ej = load_edges_upper_from_csv(path, index_base_edges=index_base_edges)
            if n_meta is None:
                if ei.size == 0:
                    raise ValueError(f"Cannot infer n from empty edge list in {path}; provide meta.json.")
                n_meta = int(max(ei.max(), ej.max()) + 1)
            return int(n_meta), ei, ej

    raise FileNotFoundError(
        f"Cannot find A_upper_bitpack.bin, A_edges.csv, or edges.csv in {rep_dir}."
    )


# -----------------------------------------------------------------------------
# Edge-flipping mechanism
# -----------------------------------------------------------------------------


def _edgeflip_probs(eps: float, delta: float = 0.0) -> Tuple[float, float]:
    r"""
    Return keep and flip probabilities for symmetric randomized response.

    The implementation uses

    .. math::

        p_{\mathrm{keep}} = \frac{\exp(\epsilon)+\delta}{\exp(\epsilon)+1},
        \qquad
        q_{\mathrm{flip}} = 1 - p_{\mathrm{keep}}.

    When ``delta=0``, this is the usual edge-flipping randomized response.
    """
    eps = float(eps)
    delta = float(delta)
    if eps <= 0:
        raise ValueError("eps must be positive.")
    if not (0.0 <= delta <= 1.0):
        raise ValueError("delta must lie in [0, 1].")

    exp_eps = np.exp(eps)
    p_keep = (exp_eps + delta) / (exp_eps + 1.0)
    q_flip = 1.0 - p_keep
    return float(np.clip(p_keep, 0.0, 1.0)), float(np.clip(q_flip, 0.0, 1.0))


def _tri_prefix(n: int) -> np.ndarray:
    """Prefix counts for the strict upper triangle."""
    counts = np.arange(n - 1, 0, -1, dtype=np.int64)
    prefix = np.zeros(n, dtype=np.int64)
    prefix[1:] = np.cumsum(counts, dtype=np.int64)
    return prefix


def _ij_to_tri_index(i: np.ndarray, j: np.ndarray, n: int, prefix: np.ndarray) -> np.ndarray:
    """Map 0-based pairs ``i < j`` to linear upper-triangle indices."""
    return prefix[i] + (j - i - 1)


def _tri_index_to_ij(k: np.ndarray, n: int, prefix: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    """Map linear upper-triangle indices to 0-based pairs ``i < j``."""
    k = np.asarray(k, dtype=np.int64)
    i = np.searchsorted(prefix, k, side="right") - 1
    off = k - prefix[i]
    j = i + 1 + off
    return i.astype(np.int64), j.astype(np.int64)


def _sample_nonedge_indices(
    n: int,
    observed_index: np.ndarray,
    add_m: int,
    rng: np.random.Generator,
    max_rounds: int = 100,
    oversample: float = 1.5,
) -> np.ndarray:
    """Sample ``add_m`` distinct non-edge upper-triangle indices."""
    if add_m <= 0:
        return np.empty(0, dtype=np.int64)

    total_pairs = n * (n - 1) // 2
    observed_index = np.asarray(observed_index, dtype=np.int64)
    observed_index = np.unique(observed_index)

    selected_chunks: list[np.ndarray] = []
    selected_count = 0
    selected_so_far = np.empty(0, dtype=np.int64)

    # Rejection sampling.  This is efficient when add_m is not too close to the
    # total number of non-edges.  It also avoids constructing the full set of
    # non-edge IDs, which would be very large for n=20,000.
    for _round in range(max_rounds):
        need = add_m - selected_count
        if need <= 0:
            break

        draw_size = max(int(np.ceil(oversample * need)), need + 1024)
        cand = rng.integers(0, total_pairs, size=draw_size, dtype=np.int64)
        cand = np.unique(cand)

        keep = ~np.isin(cand, observed_index, assume_unique=False)
        if selected_so_far.size > 0:
            keep &= ~np.isin(cand, selected_so_far, assume_unique=False)
        cand = cand[keep]
        if cand.size == 0:
            continue

        take = cand[:need]
        selected_chunks.append(take)
        selected_count += int(take.size)
        selected_so_far = np.concatenate(selected_chunks) if selected_chunks else np.empty(0, dtype=np.int64)

    if selected_count < add_m:
        raise RuntimeError(
            f"Failed to sample enough non-edges: requested {add_m}, got {selected_count}. "
            "Try increasing max_rounds or using a larger epsilon."
        )

    out = np.concatenate(selected_chunks)[:add_m]
    return np.unique(out)[:add_m]


def edgeflip_upper_edges(
    n: int,
    ei: np.ndarray,
    ej: np.ndarray,
    eps: float,
    rng: np.random.Generator,
    delta: float = 0.0,
    max_added_non_edges: Optional[int] = None,
) -> Tuple[np.ndarray, np.ndarray, float, float, int, int]:
    """
    Apply edge flipping to upper-triangle edges.

    Returns
    -------
    ei_private, ej_private:
        Upper-triangle edge arrays of the privatized graph.
    p_keep, q_flip:
        Edge keep and non-edge flip probabilities.
    n_kept, n_added:
        Number of original edges retained and number of non-edges added.
    """
    ei = np.asarray(ei, dtype=np.int64)
    ej = np.asarray(ej, dtype=np.int64)
    if ei.shape != ej.shape:
        raise ValueError("ei and ej must have the same shape.")
    if np.any(ei == ej):
        raise ValueError("Input edge arrays must contain strict upper-triangle edges only.")

    swap = ei > ej
    if np.any(swap):
        tmp = ei[swap].copy()
        ei[swap] = ej[swap]
        ej[swap] = tmp

    p_keep, q_flip = _edgeflip_probs(eps=eps, delta=delta)
    m = int(ei.size)
    keep_mask = rng.random(m) < p_keep
    ei_keep = ei[keep_mask]
    ej_keep = ej[keep_mask]

    total_pairs = n * (n - 1) // 2
    n_non_edges = total_pairs - m
    n_added = int(rng.binomial(n_non_edges, q_flip))

    if max_added_non_edges is not None and n_added > int(max_added_non_edges):
        raise MemoryError(
            f"EdgeFlip would add {n_added:,} non-edges, exceeding max_added_non_edges="
            f"{int(max_added_non_edges):,}.  Increase epsilon, raise the cap, or run on a machine "
            "with enough memory for the privatized graph."
        )

    if n_added == 0:
        return ei_keep, ej_keep, p_keep, q_flip, int(ei_keep.size), 0

    prefix = _tri_prefix(n)
    obs_index = _ij_to_tri_index(ei, ej, n=n, prefix=prefix)
    add_index = _sample_nonedge_indices(n=n, observed_index=obs_index, add_m=n_added, rng=rng)
    ei_add, ej_add = _tri_index_to_ij(add_index, n=n, prefix=prefix)

    ei_private = np.concatenate([ei_keep, ei_add])
    ej_private = np.concatenate([ej_keep, ej_add])
    return ei_private, ej_private, p_keep, q_flip, int(ei_keep.size), int(ei_add.size)


def _build_sparse_A_from_upper_edges(n: int, ei: np.ndarray, ej: np.ndarray):
    """Build a symmetric CSR adjacency matrix from upper-triangle edges."""
    m = int(ei.size)
    if m == 0:
        return coo_matrix((n, n), dtype=float).tocsr()

    data = np.ones(2 * m, dtype=float)
    rows = np.concatenate([ei, ej])
    cols = np.concatenate([ej, ei])
    return coo_matrix((data, (rows, cols)), shape=(n, n), dtype=float).tocsr()


def _top_abs_eigvecs(A_csr, K: int) -> np.ndarray:
    """Return the top-K eigenvectors by absolute eigenvalue magnitude."""
    n = A_csr.shape[0]
    if K >= n:
        raise ValueError(f"Need K < n for eigsh; got K={K}, n={n}.")
    vals, vecs = eigsh(A_csr, k=K, which="LM")
    order = np.argsort(np.abs(vals))[::-1]
    return vecs[:, order[:K]].astype(float)


# -----------------------------------------------------------------------------
# Public experiment runner
# -----------------------------------------------------------------------------


def run_edgeflip_from_saved(
    sim_dir: str | Path,
    rep_ids: Sequence[int],
    K: int,
    eps_list: Iterable[float],
    delta: float = 0.0,
    nstart: int = 25,
    base_seed: int = 5000,
    verbose: bool = True,
    index_base_edges: Optional[int] = 1,
    max_added_non_edges: Optional[int] = None,
) -> pd.DataFrame:
    """
    Run the EdgeFlip baseline on saved simulation replications.

    Parameters
    ----------
    sim_dir:
        Scenario folder containing replication subfolders.
    rep_ids:
        Replication IDs to use.
    K:
        Number of communities.
    eps_list:
        Privacy budgets for EdgeFlip.  In Experiment 2 these are the total
        budgets ``eps_all``.
    delta:
        Approximate-DP slack used in the keep/flip probabilities.  Set to 0 for
        the standard pure-DP randomized response version.
    nstart:
        Number of k-means initializations.
    base_seed:
        Base random seed.  The actual seed depends on both replication and
        privacy budget index.
    verbose:
        If True, print one line per run.
    index_base_edges:
        Index base for CSV edge lists.  Bit-packed files are decoded as 0-based
        internally regardless of this value.
    max_added_non_edges:
        Optional safety cap on the number of non-edges added by EdgeFlip.
    """
    sim_dir = Path(sim_dir)
    eps_values = [float(eps) for eps in eps_list]

    rows: list[dict] = []
    for rep in rep_ids:
        rep_dir = _find_rep_dir(sim_dir, int(rep))
        n, ei, ej = load_saved_upper_edges(rep_dir, index_base_edges=index_base_edges)
        z_true = try_load_labels_true(str(rep_dir))
        if z_true is None:
            raise FileNotFoundError(f"Cannot load true labels from {rep_dir}.")
        z_true = np.asarray(z_true, dtype=int).reshape(-1)
        if z_true.size != n:
            raise ValueError(f"Label length mismatch in {rep_dir}: len(z)={z_true.size}, n={n}.")

        for eps_idx, eps in enumerate(eps_values):
            seed = int(base_seed + 1_000_003 * int(rep) + eps_idx)
            rng = np.random.default_rng(seed)

            ei_priv, ej_priv, p_keep, q_flip, n_kept, n_added = edgeflip_upper_edges(
                n=n,
                ei=ei,
                ej=ej,
                eps=eps,
                rng=rng,
                delta=delta,
                max_added_non_edges=max_added_non_edges,
            )
            A_priv = _build_sparse_A_from_upper_edges(n=n, ei=ei_priv, ej=ej_priv)
            Xi_priv = _top_abs_eigvecs(A_priv, K=K)
            labels = _cluster_from_embedding(
                Xi_priv,
                K=K,
                nstart=nstart,
                seed=base_seed + int(rep),
            )
            err = clustering_error(z_true, labels)

            rows.append(
                dict(
                    rep=int(rep),
                    eps=float(eps),
                    delta=float(delta),
                    clustering_error_vs_truth=float(err),
                    n=int(n),
                    num_edges_original=int(ei.size),
                    num_edges_private=int(ei_priv.size),
                    num_edges_kept=int(n_kept),
                    num_non_edges_added=int(n_added),
                    p_keep=float(p_keep),
                    q_flip=float(q_flip),
                    seed=int(seed),
                )
            )

            if verbose:
                print(
                    f"[EdgeFlip] rep={int(rep):03d}, eps={eps:.4g}, "
                    f"err={err:.6f}, kept={n_kept:,}, added={n_added:,}"
                )

    return pd.DataFrame(rows)


__all__ = [
    "run_edgeflip_from_saved",
    "edgeflip_upper_edges",
    "load_saved_upper_edges",
    "load_edges_upper_from_bitpack",
    "load_edges_upper_from_csv",
]
